services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  adminer:
    image: adminer
    ports:
      - 8000:8080
    networks:
      - backend

  app:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    external: false
volumes:
  pgdata:
