import { Metadata } from "next";

export const metadataEn: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const metadataFr: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
